name: Upload
on:
  release:
    types: [created]

jobs:
  upload:
    name: Upload dist archive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Create dist archive
        run: npm pack

      - name: Upload dist archive
        uses: AButler/upload-release-assets@e940f6342206c9655b12a28a79646d3982571ad9
        with:
          files: 'metadata-filter-*.tgz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
